<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.kie</groupId>
  <artifactId>pmmljar</artifactId>
  <version>2.0</version>
  <packaging>kjar</packaging>

  <properties>
    <generateModel>NO</generateModel>
    <generateDMNModel>NO</generateDMNModel>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <version.org.drools>7.67.2.Final-redhat-00054</version.org.drools>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-model-compiler</artifactId>
      <version>${version.org.drools}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-pmml-dependencies</artifactId>
      <version>${version.org.drools}</version>
      <scope>provided</scope>
      <exclusions>
        <!-- Tree -->
        <exclusion>
          <groupId>org.kie</groupId>
          <artifactId>kie-pmml-models-drools-tree-model</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.kie</groupId>
          <artifactId>kie-pmml-models-drools-tree-compiler</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.kie</groupId>
          <artifactId>kie-pmml-models-drools-tree-evaluator</artifactId>
        </exclusion>
      </exclusions>
      <!--      <scope>provided</scope>-->
    </dependency>
    <!-- Tree -->
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-pmml-models-tree-model</artifactId>
      <version>${version.org.drools}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-pmml-models-tree-compiler</artifactId>
      <version>${version.org.drools}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.kie</groupId>
      <artifactId>kie-pmml-models-tree-evaluator</artifactId>
      <version>${version.org.drools}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>RELEASE</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.16.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.kie.server</groupId>
      <artifactId>kie-server-client</artifactId>
      <version>7.67.2.Final-redhat-00054</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>properties-maven-plugin</artifactId>
          <version>1.0.0</version>
        </plugin>
        <plugin>
          <groupId>org.kie</groupId>
          <artifactId>kie-maven-plugin</artifactId>
          <version>${version.org.drools}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>properties-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>set-system-properties</goal>
            </goals>
            <configuration>
              <properties>
                <property>
                  <name>kie-pmml-implementation</name>
                  <value>new</value>
                </property>
              </properties>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.kie</groupId>
        <artifactId>kie-maven-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <properties>
            <drools.dialect.java.compiler.lnglevel>11</drools.dialect.java.compiler.lnglevel>
          </properties>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>